[tox]
envlist = ansible11
skipsdist = true

[testenv]
changedir = {env:PWD}
passenv =
    MOLECULE_DISTRO
    INSTANCE_DISTRO
    TERM
    PY_COLORS
    ANSIBLE_FORCE_COLOR
deps =
    ansible11: ansible>=11.0,<12.0
    molecule
    molecule-plugins[docker]
commands_pre =
    ansible-galaxy collection install community.postgresql community.general
commands =
    molecule test
    molecule test --scenario-name custom_vars
