---
- name: Ensure bareos-storage is installed
  ansible.builtin.apt:
    name:
      - bareos-storage

- name: Configure Sd->Storage resource
  template:
    src: bareos-sd/storage/bareos-sd.conf.j2
    dest: /etc/bareos/bareos-sd.d/storage/bareos-sd.conf
    owner: bareos
    group: bareos
    mode: '0640'
  notify: Restart bareos-storage

- name: Configure Sd->Director resource
  template:
    src: bareos-sd/director/bareos-dir.conf.j2
    dest: /etc/bareos/bareos-sd.d/director/bareos-dir.conf
    owner: bareos
    group: bareos
    mode: '0640'
  notify: Restart bareos-storage

- name: Configure Storage Daemon block devices
  when: bareos_devices is defined
  block:
    - name: Create file systems
      community.general.filesystem:
        fstype: "{{ item.fstype | default('ext4') }}"
        dev: "{{ item.block_device }}"
        force: false
        state: present
      loop: "{{ bareos_devices }}"
      # Create file system only when block_device starts with '/dev/'
      when:
        - item.block_device is defined
        - item.block_device[:5] == '/dev/'

    - name: Mount Bareos block devices
      ansible.posix.mount:
        path: "{{ item.archive_device | default(item.arch_device) }}"
        src: "{{ item.block_device }}"
        fstype: "{{ item.fstype | default('ext4') }}"
        opts: "{{ item.opts | default(omit) }}"
        state: "{{ item.state | default('mounted') }}"
      loop: "{{ bareos_devices }}"
      when: item.block_device is defined

    - name: Set permissions on archive devices
      ansible.builtin.file:
        path: "{{ item.archive_device | default(item.arch_device) }}"
        owner: "bareos"
        group: "bareos"
        mode: "{{ item.mode | default('0750') }}"
        state: directory
      loop: "{{ bareos_devices }}"

- name: Configure Sd->Device resources
  template:
    src: bareos-sd/device/device.conf.j2
    dest: /etc/bareos/bareos-sd.d/device/{{ item.name }}.conf
    owner: bareos
    group: bareos
    mode: '0640'
  loop: "{{ bareos_devices }}"
  when: bareos_devices is defined
  notify: Restart bareos-storage
