---
- name: Ensure bareos server is installed
  apt:
    name:
      - bareos
      - bareos-webui
  notify: Restart apache

- name: Change default catalog password
  ansible.builtin.lineinfile:
    path: /etc/bareos/bareos-dir.d/catalog/MyCatalog.conf
    regexp: '^  dbpassword ='
    line: '  dbpassword = "{{ bareos_postgres_pass }}"'
  when: bareos_postgres_pass is defined

- name: Ensure bareos postgresql is installed
  apt:
    name: bareos-database-postgresql

- name: Ensure postgresql is installed
  apt:
    name: "{{ bareos_db_package }}"

- name: Make sure postgresql is running
  systemd:
    name: postgresql
    state: started

- name: Install packages for monitoring
  apt:
    name: "{{ bareos_apt_monitoring_packages }}"

- name: Setup bareos DB
  when: bareos_setup_db
  block:
    - name: Check that bareos DB exists
      shell: psql -lqt | cut -d \| -f 1 | grep -qw bareos
      become: true
      become_user: postgres
      register: _bareos_db_exists
      failed_when: false
      changed_when: false

    - name: Run DB setup scripts
      become: true
      become_user: postgres
      shell: >
        /usr/lib/bareos/scripts/create_bareos_database &&
        /usr/lib/bareos/scripts/make_bareos_tables &&
        /usr/lib/bareos/scripts/grant_bareos_privileges
      when: _bareos_db_exists.rc != 0

- name: Setup bareos DB monitoring
  when: bareos_setup_db_sensu
  block:
    - name: Create Postgres Monitoring User
      become: true
      become_user: postgres
      postgresql_user:
        name: sensu
        password: "{{ bareos_sensu_postgres_pass }}"

    - name: Ensure we have access from the monitoring user
      become: true
      become_user: postgres
      postgresql_privs:
        db: bareos
        role: sensu
        objs: ALL_IN_SCHEMA
        privs: SELECT

- name: Create bareos dir director config file
  template:
    src: bareos-dir/director/bareos-dir.conf.j2
    dest: /etc/bareos/bareos-dir.d/director/bareos-dir.conf
    owner: bareos
    group: bareos
    mode: '0640'

- name: Create bareos fileset config files
  template:
    src: bareos-dir/fileset/fileset.conf.j2
    dest: /etc/bareos/bareos-dir.d/fileset/{{ item.name }}.conf
    owner: bareos
    group: bareos
    mode: '0640'
  loop: "{{ bareos_filesets }}"
  when: bareos_filesets is defined

- name: Create bareos pool config files
  template:
    src: bareos-dir/pool/pool.conf.j2
    dest: /etc/bareos/bareos-dir.d/pool/{{ item.name }}.conf
    owner: bareos
    group: bareos
    mode: '0640'
  loop: "{{ bareos_pools }}"
  when: bareos_pools is defined

- name: Create bareos dir storage config files
  template:
    src: bareos-dir/storage/storage.conf.j2
    dest: /etc/bareos/bareos-dir.d/storage/{{ item.name }}.conf
    owner: bareos
    group: bareos
    mode: '0640'
  loop: "{{ bareos_dir_storage }}"
  when: bareos_dir_storage is defined

- name: Create bareos schedule config files
  template:
    src: bareos-dir/schedule/schedule.conf.j2
    dest: /etc/bareos/bareos-dir.d/schedule/{{ item.name }}.conf
    owner: bareos
    group: bareos
    mode: '0640'
  loop: "{{ bareos_schedules }}"
  when: bareos_schedules is defined

- name: Create bareos catalog job config file
  template:
    src: bareos-dir/job/BackupCatalog.conf.j2
    dest: /etc/bareos/bareos-dir.d/job/BackupCatalog.conf
    owner: bareos
    group: bareos
    mode: '0640'

- name: Create bareos messages config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: bareos
    group: bareos
    mode: '0640'
  loop:
    - { src: 'bareos-dir/messages/Daemon.conf.j2', dest: '/etc/bareos/bareos-dir.d/messages/Daemon.conf' }
    - { src: 'bareos-dir/messages/Standard.conf.j2', dest: '/etc/bareos/bareos-dir.d/messages/Standard.conf' }

- name: Add bconsole config file
  template:
    src: "bconsole.conf.j2"
    dest: /etc/bareos/bconsole.conf
    mode: 0700
    owner: bareos
    group: bareos

- name: Add webui admin console
  template:
    src: "admin.conf.j2"
    dest: /etc/bareos/bareos-dir.d/console/admin.conf
    mode: 0700
    owner: bareos
    group: bareos
  notify:
    - Reload bareos server
    - Restart apache
  when: bareos_setup_webui_admin_console

- name: Make sure daemons are started
  systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - bareos-dir
    - bareos-sd
    - bareos-fd
    - apache2

- name: Wait for apache to start
  wait_for:
    port: 80
    host: 127.0.0.1
    delay: 5
    sleep: 5
    timeout: 60

- name: Upload useful scripts
  copy:
    src: opt/bareos_utils/
    dest: /opt/bareos_utils/
    mode: 0700
    directory_mode: 0700
    owner: root
    group: root
