---
bareos_install_server: true
bareos_setup_db: true
bareos_dir_ip_eth: server
bareos_director_password: director_password
bareos_storage_password: storage_password
bareos_sensu_postgres_pass: password
bareos_clients:
  - name: "{{ lookup('env', 'REPO_NAME') }}-{{ lookup('env', 'OS_VERSION') }}-{{ lookup('env', 'REF') }}-client"
    address: client
    password: client_password
    enable_backup_job: true
    max_job_bandwidth: 100 mb/s
bareos_setup_webui_admin_console: true
bareos_excludes:
  - /usr
  - /var/lib/bareos
  - /var/lib/bareos/storage
  - /proc
  - /tmp
  - /var/tmp
  - /.journal
  - /.fsck
