---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server
    image: "quay.io/actatux/${MOLECULE_DISTRO:-debian-systemd:bullseye}"
    override_command: false
    privileged: true
    pre_build_image: true
    groups:
      - servers
  - name: client
    image: "quay.io/actatux/${MOLECULE_DISTRO:-debian-systemd:bullseye}"
    override_command: false
    privileged: true
    pre_build_image: true
    groups:
      - clients
provisioner:
  name: ansible
verifier:
  name: ansible
