---
- name: Prepare
  hosts: all
  tasks:
    - name: Install dependencies
      apt:
        update_cache: true
        name:
          - locales
          - tzdata
          - apt-transport-https
          - iputils-ping
          - iproute2
          - curl

    - name: Add server to /etc/hosts
      shell: echo "{{ hostvars[item].ansible_default_ipv4.address }} server {{ item }}" >> /etc/hosts
      with_items: "{{ groups['servers'] }}"
      changed_when: false

    - name: Add client server to /etc/hosts
      shell: echo "{{ hostvars[item].ansible_default_ipv4.address }} client {{ item }}" >> /etc/hosts
      with_items: "{{ groups['clients'] }}"
      changed_when: false
